def escape_reserved_character(input):
    return (input.replace("-", "\\-")
                 .replace("_", "\_")
                 .replace(".", "\.")
                 .replace("(", "\(")
                 .replace(")", "\)")
                 .replace("[", "\[")
                 .replace("]", "\]")
                 .replace("#", "\#")
                 .replace("{", "\{")
                 .replace("}", "\}")
                 .replace("=", "\=")
                 .replace("|", "\|")
                 .replace("!", "\!"))
